export const LOAD_PLAYDATA = 'LOAD_PLAYDATA';
export const UPDATE_PLAYDATA = 'UPDATE_PLAYDATA';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_GOLD = 'UPDATE_GOLD';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const UPDATE_SINGLEPLAY = 'UPDATE_SINGLEPLAY';
export const UPDATE_MULTIPLAY = 'UPDATE_MULTIPLAY';